const QUOTES = {
  "🎯 Deep Focus": [
    "The successful warrior is the average man, with laser-like focus. — Bruce Lee",
    "Focus is the key to success. — Unknown",
    "The difference between the impossible and the possible lies in a person’s determination. — Tommy Lasorda",
    "Concentration is the secret of strength. — Ralph Waldo Emerson",
    "Your ability to concentrate and stay focused is the key to achieving your goals. — Les Brown",
    "The more I want to get something done, the less I call it work. — Richard Bach",
    "You can’t depend on your eyes when your imagination is out of focus. — Mark Twain",
    "The greatest weapon against stress is our ability to choose one thought over another. — William James",
    "Don’t watch the clock; do what it does. Keep going. — Sam Levenson",
    "Focusing is about saying no. — Steve Jobs",
  ],
  "💗 Self-Worth": [
    "You yourself, as much as anybody in the entire universe, deserve your love and affection. — Buddha",
    "The most important relationship you will ever have is the one you have with yourself. — Diane Von Furstenberg",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. — Christian D. Larson",
    "Self-worth comes from one thing – thinking that you are worthy. — Wayne Dyer",
    "You are enough just as you are. — Meghan Markle",
    "No one can make you feel inferior without your consent. — Eleanor Roosevelt",
    "Loving yourself isn’t vanity; it’s sanity. — Katrina Mayer",
    "You are not a mistake. You are a miracle. — Unknown",
    "When you recover or discover something that is true, you feel the energy of the universe running through you. — Barbara Marciniak",
    "To love yourself is to understand you don’t need to be perfect to be good enough. — Unknown",
  ],
  "🔥 Motivation": [
    "The only way to do great work is to love what you do. — Steve Jobs",
    "Don’t watch the clock; do what it does. Keep going. — Sam Levenson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
    "It always seems impossible until it’s done. — Nelson Mandela",
    "The future depends on what we do in the present. — Mahatma Gandhi",
    "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
    "Do what you can with all you have, wherever you are. — Theodore Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. — Confucius",
    "Action is the foundational key to all success. — Pablo Picasso",
    "Hardships often prepare ordinary people for an extraordinary destiny. — C.S. Lewis",
  ],
  "🛏️ Rest & Recovery": [
    "Take rest; a field that has rested gives a bountiful crop. — Ovid",
    "Sometimes the most productive thing you can do is relax. — Mark Black",
    "Rest is not idleness, and to lie on the grass under the trees on a summer day, listening to the murmur of the water, is by no means a waste of time. — John Lubbock",
    "Sleep is the best meditation. — Dalai Lama",
    "Take care to get all things done, but don't forget to rest, for rest is a part of work. — Jim Rohn",
    "Your body needs rest, and so do you. — Unknown",
    "Sleep is that golden chain that ties health and our bodies together. — Thomas Dekker",
    "Without rest, we can't reach our potential. — Unknown",
    "Rest is essential for rejuvenation, growth, and strength. — Unknown",
    "Self-care is how you take your power back. — Lalah Delia",
  ],
  "🎨 Creative Spark": [
    "Creativity is intelligence having fun. — Albert Einstein",
    "You can’t use up creativity. The more you use, the more you have. — Maya Angelou",
    "Every artist was first an amateur. — Ralph Waldo Emerson",
    "Creativity is contagious, pass it on. — Albert Einstein",
    "The chief enemy of creativity is good sense. — Pablo Picasso",
    "The creative adult is the child who survived. — Ursula K. Le Guin",
    "Do one thing every day that scares you. — Eleanor Roosevelt",
    "Inspiration exists, but it has to find you working. — Pablo Picasso",
    "The only way to do great work is to love what you do. — Steve Jobs",
    "Creativity is the way I share my soul with the world. — Brene Brown",
  ],
};

export default QUOTES;
